### ISSUE TITLE
Slow SVG drawing due to usage of clientWidth and clientHeight

### ISSUE THREAD

**Issue by whimboo** [whimboo/perfchaser#28]
This has been reported by @smaug---- some days ago. Using one of these properties actually flushes the layout. Flushing the layout would have to happen anyway, but best would be to:

1. Get and process all the data
2. Use `requestAnimationFrame` to actually draw the SVG

**Comment by whimboo** [comment]
Here an appropriate profile: https://share.firefox.dev/3sXXyw2

**Comment by whimboo** [comment]
@smaug---- what about the following improvements:

1. Cache the SVG width and height and update the width value in case the sidebar gets resized. This would never require to call both `clientWidth` and `clientHeight`, and it will only take around 0.7ms to draw the SVG in my case.

2. Is it possible to pre-create all the polyline points and only modify their y value? Probably not.

**Comment by smaug----** [comment]
Caching the value sounds reasonable. 

Can't you tweak polyline points using the array of points:
polyline.points

**Comment by whimboo** [comment]
That's what I'm doing with the call to `setAttribute("points", ...)`. But it gets a string, and doesn't handle it as array / list.

**Comment by smaug----** [comment]
I'm not talking about setAttribute, but .points webidl attribute, which is a list.
