### ISSUE TITLE
Display histogram of CPU load for selected process

### ISSUE THREAD

**Issue by whimboo** [whimboo/perfchaser#5]
To not only see the current CPU load and memory usage of each the processes it would be great to get a histogram added to the `Details` pane for the selected process. To save CPU resources drawing the histogram should be done by some Vanilla JS  operations, which means that we do not want to use any kind of JS library for that. 

@smaug---- which technique would be great here? I'm aware of Canvas2d issues on Mac, so I would not particularly use that right now. Which other options do we have?

For the type of chart we should use a filled line-style one like most system activity monitor tools make use of. 

Also we might want to show both the kernel (system) and user CPU load.

**Comment by smaug----** [comment]
Canvas2d should work everywhere, otherwise websites would be rather broken.
But, perhaps svg would be bit lighter weight for this (at least from garbage collection point of view), and even easier to implement.
One could have predefined elements to define the histogram and then over the time one just tweaks the attribute values of those elements.

**Comment by whimboo** [comment]
> Canvas2d should work everywhere, otherwise websites would be rather broken.

Yes, but on MacOS we have huge performance issues here, and it's not clear yet when those will be fixed. As such I would not use it for now. But maybe the amount of drawing we do here is not that to see the effect. Might be worth to investigate.

> But, perhaps svg would be bit lighter weight for this (at least from garbage collection point of view), and even easier to implement.
> One could have predefined elements to define the histogram and then over the time one just tweaks the attribute values of those elements.

Do you have some examples? I would like to have a look into that. 

Also I just filed issue #9 to get a cyclic buffer implemented in background.js. It would allow us to not have to start from a clean histogram but might already have a couple of entries included.

**Comment by smaug----** [comment]
There are many options: Smooth bezier curves
https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Paths#b%C3%A9zier_curves
or simpler https://developer.mozilla.org/en-US/docs/Web/SVG/Element/polyline
etc.

**Comment by whimboo** [comment]
For now lets just go with the CPU load chart. We could check about adding another one for memory later.
