### ISSUE TITLE
Access code in background script directly (no sending of messages)

### ISSUE THREAD

**Issue by whimboo** [whimboo/perfchaser#6]
Right now the sidebar code sends messages to the background script to request updated data. This is causing lots of overhead for serialization and de-serialization especially with a lot of web content processes.

With [runtime.getBackgroundPage()](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/getBackgroundPage) we would be able to access code directly with the caveat that it won't work for Private Browsing windows. Hereby we might have to fallback to continue sending messages.

I don't see support for Private Browsing that important right now compared to the CPU overhead the sending of messages is currently causing.

CCing @smaug---- who made me aware of this overhead.

**Comment by smaug----** [comment]
Can you really access the chrome APIs from the extension process? I thought there would always be some messaging.

**Comment by whimboo** [comment]
Yes, any communication with the WebExperiments API will be done via messages. That's something we cannot change. But that's not the point for this issue, which is about `Background script` <-> `Sidebar script`.

**Comment by whimboo** [comment]
@smaug---- could you have a look if that performs better for you now? At least on my side I can see a CPU reduction of 66% on the extension process.

**Comment by smaug----** [comment]
It doesn't seem to take too much cpu time. Message passing obviously is still the biggest part and then that layout flush.

**Comment by whimboo** [comment]
We cannot get around the message passing part between the main process (experimental API) and webextension process. But beside that no other message passing should actually happening. Or does it?
